version: '3.7'
services:

  # SQL database
  postgres:
    image: "postgres:17"
    volumes:
      - "tilleggsstonader-klage-data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "tilleggsstonader-klage"

  tilleggsstonader-htmlify:
    image: "ghcr.io/navikt/tilleggsstonader-htmlify:latest"
    ports:
      - "8001:8001"

volumes:
  tilleggsstonader-klage-data: