/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "tilleggsstonader-klage"

// Avkommenter hvis du vl bruke en lokal versjon av kontrakter
// includeBuild("../tilleggsstonader-kontrakter")
