#######
# Denne er brukt til å gjøre det mulig å bruke tokens lokalt
#
# secret kan hentes fra cluster med "kubectl -n tilleggsstonader get secret azuread-tilleggsstonader-klage-lokal -o json | jq '.data | map_values(@base64d)'"
#
# Kjøres en gang eller ved endringer med
# kubectl apply -f .nais/azure-ad-app-lokal.yaml
###
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: tilleggsstonader-klage-lokal
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
spec:
  preAuthorizedApplications:
    - application: tilleggsstonader-sak-frontend-lokal
      cluster: dev-gcp
      namespace: tilleggsstonader
    - application: familie-prosessering-lokal
      cluster: dev-gcp
      namespace: teamfamilie
    - application: tilleggsstonader-sak-lokal
      cluster: dev-gcp
      namespace: tilleggsstonader
  tenant: trygdeetaten.no
  secretName: azuread-tilleggsstonader-klage-lokal
  claims:
    groups:
      - id: "3611981f-eda7-46ab-b8f2-50c3159e101c" # 0000-GA-Tilleggsstonader-Veileder
      - id: "31a99292-9461-40bf-b2d0-a815697dfbb4" # 0000-GA-Tilleggsstonader-Saksbehandler
      - id: "dab3f549-f5f0-4a9c-9f5b-1f6a15ae8424" # 0000-GA-Tilleggsstonader-Beslutter
      - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
      - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
      - id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
      - id: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS - tilgang til prosessering
    extra:
      - "NAVident"
