apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tilleggsstonader-klage
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader

spec:
  image: {{ image }}
  ingresses:
    - https://tilleggsstonader-klage.intern.dev.nav.no
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 256Mi
      cpu: 200m
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_17 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        cascadingDelete: false
        highAvailability: false
        pointInTimeRecovery: true
        tier: db-f1-micro
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: tilleggsstonader-klage
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: tilleggsstonader-sak-frontend
        - application: tilleggsstonader-sak-frontend-lokal
        - application: tilleggsstonader-sak
        - application: tilleggsstonader-prosessering
    outbound:
      rules:
        - application: tilleggsstonader-sak
        - application: tilleggsstonader-integrasjoner
        - application: familie-brev
          namespace: teamfamilie
        - application: familie-dokument
          namespace: teamfamilie
        - application: kabal-api
          namespace: klage
      external:
        - host: pdl-api.dev-fss-pub.nais.io

  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
          - "azp_name"
        groups:
          - id: "3611981f-eda7-46ab-b8f2-50c3159e101c" # 0000-GA-Tilleggsstonader-Veileder
          - id: "31a99292-9461-40bf-b2d0-a815697dfbb4" # 0000-GA-Tilleggsstonader-Saksbehandler
          - id: "dab3f549-f5f0-4a9c-9f5b-1f6a15ae8424" # 0000-GA-Tilleggsstonader-Beslutter
          - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
          - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
          - id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS gir alle tilgang i preprod til prosessering
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev