application:
  name: tilleggsstonader-klage
server:
  servlet:
    context-path: /
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

springdoc:
  packagesToScan: no.nav.tilleggsstonader.klage
  pathsToMatch: /v3/api-docs,/api/**
  swagger-ui:
    disable-swagger-default-url: true

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
  client:
    registration:
      tilleggsstonader-integrasjoner:
        resource-url: ${TILLEGGSSTONADER_INTEGRASJONER_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${TILLEGGSSTONADER_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      tilleggsstonader-integrasjoner-clientcredentials:
        resource-url: ${TILLEGGSSTONADER_INTEGRASJONER_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${TILLEGGSSTONADER_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl:
        resource-url: ${PDL_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${PDL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl-clientcredentials:
        resource-url: ${PDL_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${PDL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      kabal:
        resource-url: ${KABAL_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${KABAL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      kabal-clientcredentials:
        resource-url: ${KABAL_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${KABAL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      tilleggsstonader-sak:
        resource-url: ${TILLEGGSSTONADER_SAK_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${TILLEGGSSTONADER_SAK_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      tilleggsstonadder-sak-clientcredentials:
        resource-url: ${TILLEGGSSTONADER_SAK_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${TILLEGGSSTONADER_SAK_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

spring:
  jackson:
    deserialization:
      FAIL_ON_NULL_FOR_PRIMITIVES: true
  mvc:
    format:
      date: iso
      date-time: iso
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  data:
    jdbc:
      repositories:
        enabled: true
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  flyway:
    enabled: true
    placeholders:
      ignoreIfProd:
  datasource:
    url: ${DB_JDBC_URL}
    hikari:
      maximum-pool-size: 20
      connection-test-query: "select 1"
      max-lifetime: 30000
      minimum-idle: 1
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security:
        protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          type: PKCS12
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
    producer:
      acks: all
    consumer:
      group-id: tilleggsstonader-klage-test
      max-poll-records: 1
      auto-offset-reset: latest
      enable-auto-commit: false
management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  prometheus.metrics.export.enabled: true

DEPLOY_ENV: prod
ON_PREM_URL_ENV: prod

AZURE_APP_TENANT_ID: navq.onmicrosoft.com
AZUREAD_TOKEN_ENDPOINT_URL: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token

TILLEGGSSTONADER_HTMLIFY_URL: http://tilleggsstonader-htmlify
FAMILIE_DOKUMENT_URL: http://familie-dokument.teamfamilie

TILLEGGSSTONADER_SAK_URL: http://tilleggsstonader-sak
TILLEGGSSTONADER_SAK_SCOPE: api://${DEPLOY_ENV}-gcp.tilleggsstonader.tilleggsstonader-sak/.default

PDL_URL: https://pdl-api.${ON_PREM_URL_ENV}-fss-pub.nais.io
PDL_SCOPE: api://${DEPLOY_ENV}-fss.pdl.pdl-api/.default

TILLEGGSSTONADER_INTEGRASJONER_URL: http://tilleggsstonader-integrasjoner
TILLEGGSSTONADER_INTEGRASJONER_SCOPE: api://${DEPLOY_ENV}-gcp.tilleggsstonader.tilleggsstonader-integrasjoner/.default
TILLEGGSSTONADER_OPPGAVE_URL: ${TILLEGGSSTONADER_INTEGRASJONER_URL}

KABAL_URL: http://kabal-api.klage
KABAL_SCOPE: api://${DEPLOY_ENV}-gcp.klage.kabal-api/.default

rolle:
  ts:
    veileder: "0f841c83-0d64-407c-80d5-4eb51dfaee1e"
    beslutter: "224b5097-d0af-462c-8d8e-49c0e8a42661"
    saksbehandler: "c1e9edec-0c10-4df2-8c74-324ab9922220"

prosessering:
  rolle: "9f2c914f-9619-41a2-bea6-d62910514c8a" # Team Tilleggsstønader - Utviklere - tilgang til prosessering
  continuousRunning.enabled: true
  fixedDelayString:
    in:
      milliseconds: 15000
  delete:
    after:
      weeks: 16

lenker:
  TILLEGGSSTONADER_SAK_FRONTEND_URL: "https://tilleggstonader.nav.no/"


BEHANDLINGSSTATISTIKK_TOPIC: tilleggsstonader.aapen-tilleggsstonader-dvh-behandling