spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

DEPLOY_ENV: dev
ON_PREM_URL_ENV: dev

KABAL_URL: http://kabal-api.klage

rolle:
  ts:
    veileder: "3611981f-eda7-46ab-b8f2-50c3159e101c"
    beslutter: "dab3f549-f5f0-4a9c-9f5b-1f6a15ae8424"
    saksbehandler: "31a99292-9461-40bf-b2d0-a815697dfbb4"

PDL_URL: https://pdl-api-q1.${ON_PREM_URL_ENV}-fss-pub.nais.io
PDL_SCOPE: api://${ON_PREM_URL_ENV}-fss.pdl.pdl-api-q1/.default

lenker:
  TILLEGGSSTONADER_SAK_FRONTEND_URL: "https://tilleggsstonader.intern.dev.nav.no"

prosessering.rolle: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS

BEHANDLINGSSTATISTIKK_TOPIC: tilleggsstonader.aapen-tilleggsstonader-dvh-behandling-test