on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Run ktlint
        run: ./gradlew spotlessCheck
      - name: Test and build
        run: ./gradlew build -PskipLint
