name: Manuell deploy til prod
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: "Bygger app og deployer til prod"
    uses: navikt/tilleggsstonader/.github/workflows/java-build-and-deploy.yml@main
    secrets: inherit
    permissions:
      id-token: "write"
    with:
      cluster: "prod-gcp"
      manifest: ".nais/prod.yaml"