apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-klage-behandlingsstatistikk
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 2160
  acl:
    - team: tilleggsstonader
      application: tilleggsstonader-klage
      access: readwrite
#    - team: ptsak
#      application: pt-sak-famklage //TODO: trenger vi pt-sak-tsklage?
#      access: read