apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-klage-behandlingsstatistikk
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720
  acl:
    - team: tilleggsstonader
      application: tilleggsstonader-klage
      access: readwrite
#    - team: ptsak
#      application: pt-sak-famklage-preprod //TODO: trenger vi pt-sak-famklage-preprod?
#      access: read
#    - team: ptsak
#      application: pt-sak-famklage-dev
#      access: read //TODO: trenger vi pt-sak-tsklage-dev?